addSbtPlugin("com.eed3si9n"       % "sbt-assembly"   % "2.3.1")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"   % "0.14.5")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.5.5")
addSbtPlugin("com.github.sbt"   % "sbt-dynver"      % "5.1.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"    % "1.20.1")
